"""Proposal presentation cleanup layered over the sell-through allocation engine.

This module deliberately does not change commercial allocation rules.
It only:
1) merges identical operational movements generated by Range + Depth phases;
2) de-duplicates repeated unfulfilled-shortage messages.
"""

import frappe
from frappe import _
from frappe.utils import flt

from stock_auto_allocation.stock_auto_allocation.doctype.stock_allocation_run.full_scope_stock_allocation_run import (
    FullScopeStockAllocationRun,
)
from stock_auto_allocation.stock_auto_allocation.doctype.stock_allocation_run.stock_allocation_run import (
    _get_transit_warehouse,
)


class ConsolidatedStockAllocationRun(FullScopeStockAllocationRun):
    """Same sell-through engine with consolidated proposal presentation."""

    def _show_summary(self, skipped, unfulfilled):
        # Preserve the existing skipped-style summary.
        if skipped:
            from collections import Counter

            counts = Counter(reason for _, reason in skipped)
            labels = {
                "No Target Sales": _("no target sales"),
                "Insufficient Range Supply": _(
                    "insufficient stock to complete the minimum range"
                ),
                "No Transfer Required": _("no transfer required"),
            }
            parts = [
                f"{count} {labels.get(reason, reason)}"
                for reason, count in counts.items()
            ]
            frappe.msgprint(
                _("{0} style(s) were skipped: {1}.").format(
                    len(skipped),
                    "; ".join(parts),
                ),
                indicator="orange",
                alert=True,
            )

        if not unfulfilled:
            return

        # The same physical shortage can be detected once in Phase 1
        # (minimum-range completion) and again in Phase 2 (sales depth).
        # It remains one shortage. Use the largest remaining shortage observed
        # for each Item Variant + Target Warehouse key; do NOT sum them.
        consolidated = {}
        for item, store, qty in unfulfilled:
            key = (item, store)
            consolidated[key] = max(
                flt(consolidated.get(key, 0)),
                flt(qty),
            )

        rows = [
            (item, store, qty)
            for (item, store), qty in sorted(
                consolidated.items(),
                key=lambda row: (row[0][0], row[0][1]),
            )
        ]

        preview = [
            f"{item} → {store} short {qty:g}"
            for item, store, qty in rows[:12]
        ]
        more = f" (+{len(rows) - 12} more)" if len(rows) > 12 else ""

        frappe.msgprint(
            _(
                "Some commercially justified needs could not be covered: {0}{1}"
            ).format(
                "; ".join(preview),
                more,
            ),
            indicator="orange",
            alert=True,
        )

    def _append_proposal(
        self,
        template,
        variant,
        source,
        destination,
        qty,
        tier,
        source_stock,
        source_sales,
        source_protection_qty,
        target_stock,
        target_sales,
        target_required_qty,
        source_days_cover_value,
        target_days_cover_value,
    ):
        if flt(qty) <= 0 or source == destination:
            return

        transit = _get_transit_warehouse(destination)

        # Range completion and sales-depth are separate calculations, but if
        # both produce the exact same physical movement the Inventory Manager
        # should receive one proposal row.
        #
        # Consolidation key:
        #   Item Variant + Source + Target + Transit
        #
        # Movements from different sources are intentionally NOT combined.
        for line in self.proposal_lines:
            if (
                line.item_code == variant
                and line.source_warehouse == source
                and line.target_warehouse == destination
                and line.transit_warehouse == transit
                and line.status == "Proposed"
            ):
                line.qty = flt(line.qty) + flt(qty)

                # Preserve proposal-time audit values. If Phase 2 applies a
                # stronger protection/requirement floor, keep the higher value.
                line.source_stock = source_stock
                line.source_sales = source_sales
                line.source_protection_qty = max(
                    flt(line.source_protection_qty),
                    flt(source_protection_qty),
                )
                line.target_stock = target_stock
                line.target_sales = target_sales
                line.target_required_qty = max(
                    flt(line.target_required_qty),
                    flt(target_required_qty),
                )

                if line.source_days_cover is None:
                    line.source_days_cover = source_days_cover_value
                if line.target_days_cover is None:
                    line.target_days_cover = target_days_cover_value
                return

        self.append(
            "proposal_lines",
            {
                "item_template": template,
                "item_code": variant,
                "source_warehouse": source,
                "target_warehouse": destination,
                "transit_warehouse": transit,
                "qty": qty,
                "tier": tier,
                "status": "Proposed",
                "source_stock": source_stock,
                "source_sales": source_sales,
                "source_protection_qty": source_protection_qty,
                "source_days_cover": source_days_cover_value,
                "target_stock": target_stock,
                "target_sales": target_sales,
                "target_required_qty": target_required_qty,
                "target_days_cover": target_days_cover_value,
            },
        )
