import frappe
from frappe.custom.doctype.custom_field.custom_field import create_custom_fields

# Custom fields required by the Stock Auto-Allocation Module, created on
# "Warehouse", "Stock Entry" and "Material Request".
#
# NOTE: the Item-level filter fields (item_year, season, collection,
# custom_drop) are NOT created here -- they already exist on this site's
# Item doctype. See stock_allocation_run.py get_items() for the exact
# fieldnames used in the filter query.
CUSTOM_FIELDS = {
	"Warehouse": [
		{
			"fieldname": "stock_alloc_section",
			"label": "Stock Allocation",
			"fieldtype": "Section Break",
			"insert_after": "warehouse_type",
			"collapsible": 1,
		},
		{
			"fieldname": "custom_is_store",
			"label": "Is Store (used in Allocation)",
			"fieldtype": "Check",
			"insert_after": "stock_alloc_section",
			"description": "Marks this warehouse as a retail store eligible to receive/source stock in allocation runs.",
		},
		{
			"fieldname": "custom_is_distribution_center",
			"label": "Is Distribution Center (used in Allocation)",
			"fieldtype": "Check",
			"insert_after": "custom_is_store",
			"description": "Marks this warehouse as the DC / source warehouse for Tier 1 allocation.",
		},
		{
			"fieldname": "custom_is_transit",
			"label": "Is Transit Warehouse (used in Allocation)",
			"fieldtype": "Check",
			"insert_after": "custom_is_distribution_center",
			"description": "Marks this warehouse as a transit warehouse. Transit warehouses are excluded from store ranking/balance calculations -- they are only used as the intermediate target for Material Requests.",
		},
		{
			"fieldname": "custom_transit_warehouse",
			"label": "Transit Warehouse (for Allocation)",
			"fieldtype": "Link",
			"options": "Warehouse",
			"insert_after": "custom_is_transit",
			"description": (
				"Only relevant for Store warehouses. The transit warehouse stock is "
				"requested into before this store's manager moves it into the store. "
				"If left blank, the app will look for a warehouse named 'T-<this warehouse's "
				"name>' automatically."
			),
		},
	],
	"Stock Entry": [
		{
			"fieldname": "stock_auto_allocation_run",
			"label": "Stock Allocation Run",
			"fieldtype": "Link",
			"options": "Stock Allocation Run",
			"insert_after": "stock_entry_type",
			"read_only": 1,
			"description": "Set automatically if this Stock Entry was generated by the Stock Auto-Allocation Module (reserved for the Transit -> Store leg in a future version).",
		},
	],
	"Material Request": [
		{
			"fieldname": "stock_auto_allocation_run",
			"label": "Stock Allocation Run",
			"fieldtype": "Link",
			"options": "Stock Allocation Run",
			"insert_after": "material_request_type",
			"read_only": 1,
			"description": "Set automatically when this Material Request was generated by the Stock Auto-Allocation Module.",
		},
	],
}

ROLE_NAME = "Stock Allocation Manager"


def after_install():
	create_custom_fields(CUSTOM_FIELDS, update=True)
	create_role()
	frappe.db.commit()


def create_role():
	if not frappe.db.exists("Role", ROLE_NAME):
		role = frappe.get_doc(
			{
				"doctype": "Role",
				"role_name": ROLE_NAME,
				"desk_access": 1,
			}
		)
		role.insert(ignore_permissions=True)
